# Generated by Django 3.0.3 on 2020-02-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_food', '0002_delete_userfavoriteproducts'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='substitute_food.FavoriteProduct'),
        ),
    ]
