# Generated by Django 3.0.3 on 2020-04-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
    ]
