# Generated by Django 3.0.3 on 2020-04-27 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('substitute_food', '0002_delete_userfavoriteproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproduct',
            name='user_rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
