# Generated by Django 3.0.3 on 2020-04-28 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_food', '0003_favoriteproduct_user_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
