# Generated by Django 3.0.8 on 2020-11-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_food', '0004_favoriteproduct_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'ordering': ['product'], 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
    ]
