# Generated by Django 3.1.3 on 2020-11-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_food', '0005_auto_20201112_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name'], 'verbose_name': 'Produit'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imgURL',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productURL',
            new_name='product_url',
        ),
    ]
