# Generated by Django 3.1.3 on 2020-11-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_food', '0006_auto_20201115_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, unique=True)),
                ('products', models.ManyToManyField(to='substitute_food.Product')),
            ],
            options={
                'verbose_name': 'Magasin',
                'ordering': ['store_name'],
            },
        ),
    ]
