# Generated by Django 3.1.3 on 2020-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_food', '0007_auto_20201116_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='in_cat', to='substitute_food.Product'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='products',
            field=models.ManyToManyField(related_name='in_store', to='substitute_food.Product'),
        ),
    ]
